// Módulo de permissão (codigo em modulos_sistema) exigido por rota.
// Usado pelo guarda de rota (App.tsx) e pelo filtro do menu (AppSidebar.tsx).
// Rotas ausentes aqui não exigem permissão (ex: "/" Dashboard).
export const ROTA_MODULO: Record<string, string> = {
  "/alunos": "alunos",
  "/carteirinhas": "carteirinhas",
  "/matriculas": "matriculas",
  "/rematricula": "matriculas",
  "/turmas": "turmas",
  "/categorias": "turmas",
  "/disciplinas": "turmas",
  "/horarios": "turmas",
  "/matrizes-curriculares": "turmas",
  "/calendario": "calendario",
  "/financeiro": "financeiro",
  "/faturamento": "financeiro",
  "/parametrizacoes-financeiras": "financeiro",
  "/planos-financeiros": "financeiro",
  "/contratos": "financeiro",
  "/contas-a-pagar": "compras",
  "/compras": "compras",
  "/contas-bancarias": "conciliacao",
  "/cursos-extras": "cursos_extra",
  "/professores": "rh",
  "/funcionarios": "rh",
  "/pagamentos-professores": "rh",
  "/pagamentos-funcionarios": "rh",
  "/notas": "pedagogico",
  "/frequencia": "pedagogico",
  "/ocorrencias": "ocorrencias",
  "/avisos": "comunicacao",
  "/documentos": "relatorios_documentos",
  "/documentos/gerar": "relatorios_documentos",
  "/fornecedores": "parceiros",
  "/configuracoes": "configuracoes",
  "/filiais": "configuracoes",
  "/admin": "configuracoes",
};
